plot(iris$Sepal.Length, iris$Sepal.Width)
points(irs$Petal.Length, iris$Sepal.Width, color = "red")

# same thing with ggplot
ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point() +
  geom_point(aes(x = Petal.Length, y = Petal.Width), col = "red")

# Plotting space is adjusted
#ggplot2 produces an object

# dont do that ! we plot only what we need the variable length and width

str(iris.wid)
#good way to do it
ggplot(iris.wid, aes(x = length, y = Width, col = Part)) +
         geom_point()
       
head(iris.wid)
  
iris.wid <- (structure(list(Species = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 
                                                  1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                  1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                  1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                  1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                  1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
                                                  1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 
                                                  2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                  2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                  2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                  2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                  2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                  2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 
                                                  2L, 2L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                  3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                  3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                  3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                  3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                  3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 3L, 
                                                  3L, 3L, 3L, 3L, 3L, 3L), .Label = c("setosa", "versicolor", "virginica"
                                                  ), class = "factor"), Part = c("Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", "Petal", 
                                                                                 "Petal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", "Sepal", 
                                                                                 "Sepal", "Sepal"), Length = c(1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 
                                                                                                               1.5, 1.4, 1.5, 1.5, 1.6, 1.4, 1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 
                                                                                                               1.7, 1.5, 1, 1.7, 1.9, 1.6, 1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 
                                                                                                               1.4, 1.5, 1.2, 1.3, 1.4, 1.3, 1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 
                                                                                                               1.6, 1.4, 1.5, 1.4, 5.1, 4.9, 4.7, 4.6, 5, 5.4, 4.6, 5, 4.4, 
                                                                                                               4.9, 5.4, 4.8, 4.8, 4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 
                                                                                                               4.6, 5.1, 4.8, 5, 5, 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 
                                                                                                               5, 5.5, 4.9, 4.4, 5.1, 5, 4.5, 4.4, 5, 5.1, 4.8, 5.1, 4.6, 5.3, 
                                                                                                               5, 4.7, 4.5, 4.9, 4, 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 
                                                                                                               4, 4.7, 3.6, 4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4, 4.9, 4.7, 4.3, 
                                                                                                               4.4, 4.8, 5, 4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 
                                                                                                               4.1, 4, 4.4, 4.6, 4, 3.3, 4.2, 4.2, 4.2, 4.3, 3, 4.1, 7, 6.4, 
                                                                                                               6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5, 5.9, 6, 6.1, 5.6, 
                                                                                                               6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7, 
                                                                                                               6, 5.7, 5.5, 5.5, 5.8, 6, 5.4, 6, 6.7, 6.3, 5.6, 5.5, 5.5, 6.1, 
                                                                                                               5.8, 5, 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6, 5.1, 5.9, 5.6, 5.8, 
                                                                                                               6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5, 5.1, 5.3, 5.5, 6.7, 
                                                                                                               6.9, 5, 5.7, 4.9, 6.7, 4.9, 5.7, 6, 4.8, 4.9, 5.6, 5.8, 6.1, 
                                                                                                               6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1, 5.9, 
                                                                                                               5.7, 5.2, 5, 5.2, 5.4, 5.1, 6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 
                                                                                                               7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5, 7.7, 7.7, 6, 
                                                                                                               6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2, 7.4, 7.9, 6.4, 
                                                                                                               6.3, 6.1, 7.7, 6.3, 6.4, 6, 6.9, 6.7, 6.9, 5.8, 6.8, 6.7, 6.7, 
                                                                                                               6.3, 6.5, 6.2, 5.9), Width = c(0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 
                                                                                                                                              0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 
                                                                                                                                              0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2, 0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 
                                                                                                                                              0.1, 0.2, 0.2, 0.2, 0.2, 0.1, 0.2, 0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 
                                                                                                                                              0.3, 0.2, 0.2, 0.2, 0.2, 3.5, 3, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 
                                                                                                                                              2.9, 3.1, 3.7, 3.4, 3, 3, 4, 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 
                                                                                                                                              3.6, 3.3, 3.4, 3, 3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 
                                                                                                                                              3.2, 3.5, 3.6, 3, 3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3, 3.8, 3.2, 
                                                                                                                                              3.7, 3.3, 1.4, 1.5, 1.5, 1.3, 1.5, 1.3, 1.6, 1, 1.3, 1.4, 1, 
                                                                                                                                              1.5, 1, 1.4, 1.3, 1.4, 1.5, 1, 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 
                                                                                                                                              1.3, 1.4, 1.4, 1.7, 1.5, 1, 1.1, 1, 1.2, 1.6, 1.5, 1.6, 1.5, 
                                                                                                                                              1.3, 1.3, 1.3, 1.2, 1.4, 1.2, 1, 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 
                                                                                                                                              3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2, 3, 2.2, 
                                                                                                                                              2.9, 2.9, 3.1, 3, 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3, 
                                                                                                                                              2.8, 3, 2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3, 3.4, 3.1, 2.3, 3, 2.5, 
                                                                                                                                              2.6, 3, 2.6, 2.3, 2.7, 3, 2.9, 2.9, 2.5, 2.8, 2.5, 1.9, 2.1, 
                                                                                                                                              1.8, 2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2, 1.9, 2.1, 2, 2.4, 2.3, 
                                                                                                                                              1.8, 2.2, 2.3, 1.5, 2.3, 2, 2, 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 
                                                                                                                                              1.6, 1.9, 2, 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 
                                                                                                                                              1.9, 2.3, 2.5, 2.3, 1.9, 2, 2.3, 1.8, 3.3, 2.7, 3, 2.9, 3, 3, 
                                                                                                                                              2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3, 2.5, 2.8, 3.2, 3, 3.8, 2.6, 
                                                                                                                                              2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3, 2.8, 3, 2.8, 3.8, 
                                                                                                                                              2.8, 2.8, 2.6, 3, 3.4, 3.1, 3, 3.1, 3.1, 3.1, 2.7, 3.2, 3.3, 
                                                                                                                                              3, 2.5, 3, 3.4, 3)), .Names = c("Species", "Part", "Length", 
                                                                                                                                                                              "Width"), row.names = c(NA, -300L), class = "data.frame"))